### ISSUE TITLE
"TypeError: callback is not a function" after upgrading sharedb and sharedb-mongo

### ISSUE THREAD

**Issue by kbadk** [share/sharedb#105]
After upgrading ShareDB 0.11.36 to  1.0.0-beta.3 and ShareDB-Mongo 0.8.7 1.0.0-beta, I'm now getting:

```
Caught exception: TypeError: callback is not a function
TypeError: callback is not a function
    at Backend.submit (.../node_modules/sharedb/lib/backend.js:154:19)
    at module.exports (.../helpers/DocumentManager.js:17:7)
    at Object.<anonymous> (.../webstrates.js:49:62)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
```

When calling:

```javascript
share.submit(agent, collectionName, documentName, { v: 0, create: [] }, callback);
```

I've read the [CHANGELOG](https://github.com/share/sharedb/blob/master/CHANGELOG.md), but that does not seem to indicate that I have to change anything.

**Comment by kbadk** [comment]
Okay, I got it solved by adding an empty options parameter inbetween the op and the callback:

```javascript
share.submit(agent, collectionName, documentName, { v: 0, create: [] }, null, callback);
```

**Comment by nateps** [comment]
Glad you figured it out!
