### ISSUE TITLE
Malformed request crashing server

### ISSUE THREAD

**Issue by jonathanazulay** [share/sharedb#191]
Hello
I'm running the rich-text example and if I send the server something that's not valid JSON it crashes. I'm not sure if it's caused by sharedb or websocket-json-stream.

```
SyntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at WebSocket.<anonymous> (/secrets/app/node_modules/websocket-json-stream/index.js:11:51)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/secrets/app/node_modules/ws/lib/websocket.js:145:47)
    at Receiver.dataMessage (/secrets/app/node_modules/ws/lib/receiver.js:430:14)
    at Receiver.getData (/secrets/app/node_modules/ws/lib/receiver.js:368:12)
    at Receiver.startLoop (/secrets/app/node_modules/ws/lib/receiver.js:164:16)
    at Receiver.add (/secrets/app/node_modules/ws/lib/receiver.js:138:10)
    at Socket._ultron.on (/secrets/app/node_modules/ws/lib/websocket.js:143:54)
```

**Comment by rkstedman** [comment]
Thanks so much! Really appreciate the stack trace -- from reading it, it appears the error is from `websock-json-stream` as you suggested. Would you mind creating an issue in the websocket-json-stream project https://github.com/avital/websocket-json-stream? I'll close this issue for now and we can reopen if needed.
