### ISSUE TITLE
Invalid or unknown message after update from beta

### ISSUE THREAD

**Issue by IAkumaI** [share/sharedb#340]
Hi,
i tried to update to 1.0.0 from -beta and get this errors when client connected from derbyjs:
```
ShareDBError: Invalid or unknown message
at Agent._handleMessage (/opt/source/node_modules/sharedb/lib/agent.js:364:18)
at /opt/source/node_modules/sharedb/lib/agent.js:299:13
at next (/opt/source/node_modules/sharedb/lib/backend.js:188:21)
at /opt/source/node_modules/derby/lib/AppForServer.js:351:5
at next (/opt/source/node_modules/sharedb/lib/backend.js:189:5)
at /opt/source/node_modules/derby/lib/AppForServer.js:351:5
at next (/opt/source/node_modules/sharedb/lib/backend.js:189:5)
at RacerBackend.Backend.trigger (/opt/source/node_modules/sharedb/lib/backend.js:191:3)
at ClientStream.<anonymous> (/opt/source/node_modules/sharedb/lib/agent.js:294:19)
at ClientStream.emit (events.js:321:20)
```

This message is:
```
{
derby: 'app',
name: 'operator',
hash: 'bd2e6f3445b60b914d7e48f3fab4f5e4'
}
```

Which sent from https://github.com/derbyjs/derby/blob/master/lib/App.js#L324 as I think.

**Comment by ericyhwang** [comment]
That's a side effect of your change in Derby a couple months ago to auto-refresh multiple apps, not directly related to sharedb 1.0.

What did change in sharedb 1.0 is the warning logging now includes the stack trace, so that existing warning now takes up more lines in the logs and is more visible.

Some more context here:
https://github.com/derbyjs/derby/pull/568

I meant to spend some time to see if we could resolve the log spam on Derby's end, but I had some other things come up and haven't found the time yet.

**Comment by ericyhwang** [comment]
In case anyone comes across this issue, the warning spam in the logs was fixed in DerbyJS as of:

[derby@0.10.27](https://github.com/derbyjs/derby/releases/tag/v0.10.27)
