### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jiutianxuannan** [share/sharedb#484]

**Comment by jiutianxuannan** [comment]
new sharedb.Connection(this.socket)

**Comment by alecgibson** [comment]
Going to need a bit more information than this, please.

**Comment by maxfortun** [comment]
I am not sure if this is the same issue that the original author is facing, but I just hit the same error message.  
I am not sure how to replicate this, but here are some observations.

Stack trace:
```javascript
RangeError: Maximum call stack size exceeded
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:196:22)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
    at next (/root/apps/djsp-cfg-pubedit-sh-svc-sharedb/node_modules/sharedb/lib/backend.js:200:5)
    at /root/apps/djsp-cfg-pubedit-sh-svc-sharedb/bin/www:122:3
```
The code at `www:122` is calling `next()`.
```javascript
backend.use('submit', (context, next) => {
  Object.assign(context.op.m, context.agent.custom);
  context.opMetadataProjection = { username: true };
  next();
 });
```
The code at [backend.js:200](https://github.com/share/sharedb/blob/3e636d0100921c26b4bb5108ef0afd1b27f838af/lib/backend.js#L200) is calling `fn(request, next)`:

https://github.com/share/sharedb/blob/3e636d0100921c26b4bb5108ef0afd1b27f838af/lib/backend.js#L186-L203

From what I can tell, the `next`, since it is defined in the outer block with `var`, is global scoped, and thus when it is passed into `fn()` has the prior state. That aside, I do not fully understand what this code is trying to achieve. It is defining `next` as a function, and then calling the `next` it is defining from its own definition. It doesn't look to be intentional.

**Comment by maxfortun** [comment]
Looks like instead of passing `next`, the code should be passing `callback`. Adding fix to [#513].

https://github.com/share/sharedb/blob/cddf66c757fa938b6dbb944673cf6f3c8b93027d/lib/backend.js#L200

**Comment by alecgibson** [comment]
I left a comment on https://github.com/share/sharedb/pull/513 but reiterating here: I think we should open a separate PR for this change to discuss. As a heads-up, I won't have time until next week to look at it properly.
