### ISSUE TITLE
Middleware Errors Get Logged

### ISSUE THREAD

**Issue by curran** [share/sharedb#515]
Greetings,

I've been tearing my hair out trying to figure out why my server is crashing. I am attempting to implement access control middleware. It works, but even after handling the error in the callback passed to `Doc.fetch`, somehow the error seems to get thrown from somewhere else, and it causes the process to crash.

Here's the stack trace I see:

```
VizHubError
    at null.<anonymous> (/home/curran/repos/vizhub-core/packages/vizhub-plugin-access-control/src/vizRead.js:20:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error
    at wrapErrorData (/home/curran/repos/vizhub-core/node_modules/sharedb/lib/client/connection.js:263:13)
    at Connection.handleMessage (/home/curran/repos/vizhub-core/node_modules/sharedb/lib/client/connection.js:191:11)
    at StreamSocket.socket.onmessage (/home/curran/repos/vizhub-core/node_modules/sharedb/lib/client/connection.js:142:18)
    at /home/curran/repos/vizhub-core/node_modules/sharedb/lib/stream-socket.js:60:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'ERR_PERMISSION_DENIED',
  data: {
    a: 'f',
    c: 'documentInfo',
    d: 'b6b90a213d69499ca43db6a3945313ae',
    v: null
  }
}
```

The first line in the stack trace points to this line, which invokes the `next` middleware callback with an Error object:

```
return next(new VizHubError(ERR_PERMISSION_DENIED));
```

It's surprising to me that the stack trace does not point to any other of my source files, only ShareDB internals.

Is there some place where I need to add another error handler to silence this error?

Thanks in advance!

Full code for reference: 
 * [Middleware entry point](https://github.com/vizhub-open-core/vizhub-open-core/pull/11/files#diff-ba43c2300e6a5bad4e8fb4cadd336815243029e20b36c57d561a81f52d07cb96R7)
 * [Error throwing](https://github.com/vizhub-open-core/vizhub-open-core/pull/11/files#diff-62cabc9448361cd40a4b02682a9d0b7c3673375e21e8888eb66539f7294e259eR20)
 * [Error catching](https://github.com/vizhub-open-core/vizhub-open-core/pull/11/files#diff-613d4e8508fe9e40c97a553262e638147e3fa7eceb7966fa8dbe5c7d02686a18R16)
 * [Error handling to render not found page](https://github.com/vizhub-open-core/vizhub-open-core/pull/11/files#diff-e2a47e298e112ed9bcf8a2af7297641eab02a70374bb6a6e5c22e0b9407c4a78R54)
 
 I'm guessing it's something really simple that I'm just missing.

**Comment by curran** [comment]
It was a recursive error situation in access control middleware. I [added a try/catch](https://github.com/vizhub-open-core/vizhub-open-core/commit/573256e1581a09e03be6d8a955863dc3b339a996#diff-62cabc9448361cd40a4b02682a9d0b7c3673375e21e8888eb66539f7294e259eR25), which stopped the server from crashing, but somehow the error is still being logged to the console. Not sure why/how.

**Comment by curran** [comment]
Related https://github.com/share/sharedb/issues/348

**Comment by curran** [comment]
Minimal reproduction: https://runkit.com/curran/61366cbb7c945d000988d01f

 * Forked the [original Runkit example](https://runkit.com/alecgibson/5e5634a307e329001b795978)
 * Commented out the lines that print the error to the console
 * Changed the thing passed into the callback to an instance of `Error`
 * And voila - same behavior I see in my codebase: the error is _logged to the console_. Why? How to disable?

**Comment by curran** [comment]
The docs are not clear here in terms of what kind of object one can pass in as `error`.

https://share.github.io/sharedb/middleware/registration

**Comment by curran** [comment]
Closing in favor of https://github.com/share/sharedb/issues/516
