### ISSUE TITLE
Middleware Errors Get Logged

### ISSUE THREAD

**Issue by curran** [share/sharedb#516]
There appears to be an undesirable logging of a middleware error if it is an instance of an `Error` object.

Minimal reproduction ([RunKit](https://runkit.com/curran/61366cbb7c945d000988d01f)):

```js
const ShareDB = require('sharedb');

const backend = new ShareDB();

backend.use('readSnapshots', (request, callback) => {
  // This is fine - nothing gets logged (expected behavior):
  // callback('Some error');

  // This is not fine - the error gets logged (unexpected behavior).
  callback(new Error('Some error'));
});

const connection = backend.connect();
const doc = connection.get('test', '123');
doc.fetch((error) => {
  // Nothing being logged here!
  //if (error) console.error(error);
  //console.log('doc fetched');
});
```

The docs are not clear here in terms of what kind of object one can pass in as `error`.

https://share.github.io/sharedb/middleware/registration

Should it be an instance of `Error`? Or should it be a string? Or an object that's not an `Error`?

At the very least, I would suggest to update the documentation page to note that if you do pass an instance of `Error`, it will be logged to the console and there is no way to stop this logging from happening.

**Comment by alecgibson** [comment]
For reference, this is the offending code:

https://github.com/share/sharedb/blob/3e636d0100921c26b4bb5108ef0afd1b27f838af/lib/agent.js#L285-L287

Since an `Error` has a `stack` property, it'll get logged. From the surrounding code, it looks like you can pass any of:

 - a `string`
 - any `object` with this shape: `{code: string; message: string; stack?: string}`

I agree that this is surprising. In general, I don't like how much logging ShareDB tries to do (which is why I added the ability to at least [suppress logging](https://github.com/share/sharedb/pull/258), although this is also undocumented 😅 ).

That being said, I don't know what a constructive suggestion is. The only things I can really think of are:

 - delete this logging code
 - convert `Agent` to an `Emitter` and `emit()` an event that consumers can hook into if they're interested (although I think `emit('error', ...)` is probably noisy and incorrect, since this error isn't fatal, and is being passed back to the client to handle)

**Comment by curran** [comment]
Thanks a ton for looking into this!

I can pass an object instead of an Error instance to solve the immediate issue.

**Comment by curran** [comment]
So @alecgibson , I commented out the [line you mentioned](https://github.com/share/sharedb/blob/3e636d0100921c26b4bb5108ef0afd1b27f838af/lib/agent.js#L285-L287) in ShareDB (in `node_modules`), and the error is still getting logged, even when I pass a String or an object without the `stack` property into `next`.

Here's what gets logged:

```
Error: Message
    at wrapErrorData (/home/curran/repos/vizhub-core/node_modules/sharedb/lib/client/connection.js:263:13)
    at Connection.handleMessage (/home/curran/repos/vizhub-core/node_modules/sharedb/lib/client/connection.js:191:11)
    at StreamSocket.socket.onmessage (/home/curran/repos/vizhub-core/node_modules/sharedb/lib/client/connection.js:142:18)
    at /home/curran/repos/vizhub-core/node_modules/sharedb/lib/stream-socket.js:60:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'code',
  data: {
    a: 'f',
    c: 'documentInfo',
    d: 'b6b90a213d69499ca43db6a3945313ae',
    v: null
  }
}
```

Tearing my hair out trying to get this to stop logging.

**Comment by alecgibson** [comment]
I can't see any client-side code that should log that. Maybe you have an unhandled `.on('error')`?

**Comment by curran** [comment]
That's a good lead! Will investigate that. Thank you.
