### ISSUE TITLE
use fetchSnapshot api find this error “ShareDBError: Cannot normalize legacy json0 op”

### ISSUE THREAD

**Issue by zhoyou** [share/sharedb#531]
ShareDBError: Cannot normalize legacy json0 op
    at Object.exports.applyOps (D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\ot.js:171:16)
    at Backend._buildSnapshotFromOps (D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\backend.js:839:18)
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\backend.js:767:15
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb-mongo\index.js:472:7
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\mongodb\lib\utils.js:704:5
    at handleCallback (D:\project\bytestorm-project\document-project\ot-server\node_modules\mongodb\lib\utils.js:109:55)
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\mongodb\lib\cursor.js:854:66
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\mongodb\lib\utils.js:704:5
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\mongodb\lib\cursor.js:939:9
    at Cursor._endSession (D:\project\bytestorm-project\document-project\ot-server\node_modules\mongodb\lib\core\cursor.js:404:7)
Error: Cannot normalize legacy json0 op
    at wrapErrorData (D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\client\connection.js:263:13)
    at Connection.handleMessage (D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\client\connection.js:191:11)
    at StreamSocket.socket.onmessage (D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\client\connection.js:142:18)
    at D:\project\bytestorm-project\document-project\ot-server\node_modules\sharedb\lib\stream-socket.js:60:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_OT_LEGACY_JSON0_OP_CANNOT_BE_NORMALIZED',

**Comment by alecgibson** [comment]
Could you please provide a reproduction case?

**Comment by zhoyou** [comment]
I found the cause of the problem,
The table data in the milestone is deleted, resulting in the element being undefine, throw this exception。
Thank you, brother。
