### ISSUE TITLE
`EventEmitter` memory leak warning for too many remote presence clients

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#584]
At the moment, if you have many remote clients' presence in your `Doc`, the console logs a warning:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 del listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (webpack-internal:///./node_modules/events/events.js:211:15)
    at Doc.addListener (webpack-internal:///./node_modules/events/events.js:227:10)
    at RemoteDocPresence._registerWithDoc (webpack-internal:///./node_modules/sharedb/lib/client/presence/remote-doc-presence.js:45:13)
    at new RemoteDocPresence (webpack-internal:///./node_modules/sharedb/lib/client/presence/remote-doc-presence.js:21:8)
    at DocPresence._createRemotePresence (webpack-internal:///./node_modules/sharedb/lib/client/presence/doc-presence.js:25:10)
    at eval (webpack-internal:///./node_modules/sharedb/lib/client/presence/presence.js:115:21)
    at exports.digOrCreate (webpack-internal:///./node_modules/sharedb/lib/util.js:44:48)
    at Presence._receiveUpdate (webpack-internal:///./node_modules/sharedb/lib/client/presence/presence.js:114:29)
    at Connection._handlePresence (webpack-internal:///./node_modules/sharedb/lib/client/connection.js:822:26)
    at Connection.handleMessage (webpack-internal:///./node_modules/sharedb/lib/client/connection.js:249:19)
```

This is because we [attach listeners](https://github.com/share/sharedb/blob/cc0e3382bf3df4c38c7ccc6bc52da71aff8c9f74/lib/client/presence/remote-doc-presence.js#L42-L47) for every remote client in the `Doc`.

Potential options to fix:

 1. Do nothing — let consumers determine what a "sensible" number of max listeners is. In my opinon, this isn't a particularly nice option, and I think it should be the duty of the library to deal with warnings it's generating
 2. Increment the max listeners ourselves — whenever we create a remote listener, we increment the number of allowed listeners by one (and decrement when destroying). This essentially excludes `RemoteDocPresence` from this listener count. The downside of this is that we also remove the *legitimate* warning case where consumers forget to destroy their `RemoteDocPresence
 3. Use some sort of global handler — have one event handler per doc for all remote presences. This is probably the most typical way to deal with this, although it does feel a bit like reinventing the wheel, and it potentially goes against the idea that the `Doc` should be unaware of the presence implementation. We also fall into the trap of solution 2 of not warning consumers about having lots of presence lurking in-memory (and at that point, maybe just implementing option 2 is simpler...?)
 4. Other...?

**Comment by ericyhwang** [comment]
EventEmitter max listener warning is type-specific, but only a single max can be set, for all types on that emitter https://nodejs.org/api/events.html

So probably #3 would be needed. Ideally we make it specific to the remote presence, so that other warnings are unaffected. Potentially set a higher max on that presence one.
