### ISSUE TITLE
Middleware Errors are Fatal

### ISSUE THREAD

**Issue by mgreystone** [share/sharedb#589]
I am validating a snapshot in `'commit'` middleware. If i pass an `Error` to the `next` callback, node considers this an uncaught exception & terminates. The `uncaughtException` event is dispatched. I haven't been able to find anywhere to intercept this error.

### Sample
```js
import ShareDB from 'sharedb'

const backend = new ShareDB()

backend.use('commit', (ctx, next) => {
  next(new Error('validation error'))
})

const connection = backend.connect()
const doc = connection.get('my-collection', 'my-document')

try {
  doc.create({ foo: 'bar' })
} catch (err) {
  // we never get here
  console.error(err)
}
```

### Expectation
The document should not be saved. The node process should continue.

### Actual
The error is logged twice. Node exits with code 1.

```
Error: validation error
    at file:///Users/mgreystone/src/demo-sharedb-fatal-middleware/index.js:6:8
    at next (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/backend.js:218:5)
    at Backend.trigger (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/backend.js:220:3)
    at SubmitRequest.commit (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/submit-request.js:153:11)
    at /Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/submit-request.js:146:13
    at Backend.trigger (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/backend.js:210:20)
    at SubmitRequest.apply (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/submit-request.js:139:16)
    at /Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/submit-request.js:95:22
    at /Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/db/memory.js:68:5
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: validation error
    at wrapErrorData (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/client/connection.js:268:13)
    at Connection.handleMessage (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/client/connection.js:194:11)
    at StreamSocket.socket.onmessage (/Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/client/connection.js:145:18)
    at /Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/stream-socket.js:60:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on Connection instance at:
    at /Users/mgreystone/src/demo-sharedb-fatal-middleware/node_modules/.pnpm/sharedb@3.2.2/node_modules/sharedb/lib/client/connection.js:148:20
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: undefined,
  data: {
    a: 'op',
    c: 'my-collection',
    d: 'my-document',
    v: null,
    seq: 1,
    x: {},
    create: { type: 'http://sharejs.org/types/JSONv0', data: { foo: 'bar' } }
  }
}
 ELIFECYCLE  Command failed with exit code 1.
```

### Env
node v16.16.0
macos 13.1, m1 max

**Comment by alecgibson** [comment]
The `create()` method (and everything else for that matter) expects a callback. It's asynchronous, so using a `try`/`catch` won't work.

In order to not swallow errors, if no callback is provided, it will `emit()` an error, which will indeed crash a Node.js process (and is the intended behaviour).

The solution to your problem is to correctly handle your errors:

```js
doc.create({ foo: 'bar' }, (error) => {
  if (error) {
    // handle
  }
})
```

**Comment by mgreystone** [comment]
Aha, my mistake. Works as advertised.
